# Covid-19 Impact Analysis

In [15]:
import numpy as np
import pandas as pd

In [16]:
patients=pd.read_csv('state_wise_daily.csv')

In [17]:
patients

,Date,Date_YMD,Status,Total,Hospitalized,Recovered,Deceased,Mask,Sanitizer,Oxygen,...,RJ,SK,TN,TG,TR,UP,UT,WB,UN,State
0,14-Mar-20,14-03-2020,Confirmed,81,12,120,0,10,60,48,...,3,0,1,1,0,12,0,0,0,Maharashtra
1,14-Mar-20,14-03-2020,Recovered,9,25,5,2,20,1,38,...,1,0,0,0,0,4,0,0,0,Maharashtra
2,14-Mar-20,14-03-2020,Deceased,2,85,10,4,30,0,0,...,0,0,0,0,0,0,0,0,0,Maharashtra
3,15-Mar-20,15-03-2020,Confirmed,27,89,15,0,40,41,57,...,1,0,0,2,0,1,0,0,0,Maharashtra
4,15-Mar-20,15-03-2020,Recovered,4,10,5,21,50,4,55,...,2,0,0,1,0,0,0,0,0,Maharashtra
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1786,30-Oct-21,30-10-2021,Recovered,14672,0,14,10,371,2,2,...,1,3,1172,191,8,9,6,880,0,Lakshdweep
1787,30-Oct-21,30-10-2021,Deceased,445,22,1,0,4,0,0,...,0,0,14,1,0,0,0,13,0,Lakshdweep
1788,31-Oct-21,31-10-2021,Confirmed,12907,50,20,1,212,8,5,...,2,21,1009,121,12,6,5,914,0,Lakshdweep
1789,31-Oct-21,31-10-2021,Recovered,13152,1,23,9,236,9,3,...,2,8,1183,183,2,6,9,913,0,Lakshdweep
1790,31-Oct-21,31-10-2021,Deceased,251,23,0,0,1,0,0,...,0,1,19,1,0,0,0,15,0,Lakshdweep

,Date,Date_YMD,Status,Total,Hospitalized,Recovered,Deceased,Mask,Sanitizer,Oxygen,...,RJ,SK,TN,TG,TR,UP,UT,WB,UN,State
0,14-Mar-20,14-03-2020,Confirmed,81,12,120,0,10,60,48,...,3,0,1,1,0,12,0,0,0,Maharashtra
1,14-Mar-20,14-03-2020,Recovered,9,25,5,2,20,1,38,...,1,0,0,0,0,4,0,0,0,Maharashtra
2,14-Mar-20,14-03-2020,Deceased,2,85,10,4,30,0,0,...,0,0,0,0,0,0,0,0,0,Maharashtra
3,15-Mar-20,15-03-2020,Confirmed,27,89,15,0,40,41,57,...,1,0,0,2,0,1,0,0,0,Maharashtra
4,15-Mar-20,15-03-2020,Recovered,4,10,5,21,50,4,55,...,2,0,0,1,0,0,0,0,0,Maharashtra
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1786,30-Oct-21,30-10-2021,Recovered,14672,0,14,10,371,2,2,...,1,3,1172,191,8,9,6,880,0,Lakshdweep
1787,30-Oct-21,30-10-2021,Deceased,445,22,1,0,4,0,0,...,0,0,14,1,0,0,0,13,0,Lakshdweep
1788,31-Oct-21,31-10-2021,Confirmed,12907,50,20,1,212,8,5,...,2,21,1009,121,12,6,5,914,0,Lakshdweep
1789,31-Oct-21,31-10-2021,Recovered,13152,1,23,9,236,9,3,...,2,8,1183,183,2,6,9,913,0,Lakshdweep
1790,31-Oct-21,31-10-2021,Deceased,251,23,0,0,1,0,0,...,0,1,19,1,0,0,0,15,0,Lakshdweep

### total cases

In [18]:
patients['Status'].value_counts()

Confirmed    597
Recovered    597
Deceased     597
Name: Status, dtype: int64

Confirmed    597
Recovered    597
Deceased     597
Name: Status, dtype: int64

In [19]:
"""doubt--> what is 0"""

total=patients.shape[0]

In [20]:
total

1791

1791

In [21]:
patients[patients['Status']=='Confirmed']

,Date,Date_YMD,Status,Total,Hospitalized,Recovered,Deceased,Mask,Sanitizer,Oxygen,...,RJ,SK,TN,TG,TR,UP,UT,WB,UN,State
0,14-Mar-20,14-03-2020,Confirmed,81,12,120,0,10,60,48,...,3,0,1,1,0,12,0,0,0,Maharashtra
3,15-Mar-20,15-03-2020,Confirmed,27,89,15,0,40,41,57,...,1,0,0,2,0,1,0,0,0,Maharashtra
6,16-Mar-20,16-03-2020,Confirmed,15,1,14,7,70,28,55,...,0,0,0,1,0,0,1,0,0,Maharashtra
9,17-Mar-20,17-03-2020,Confirmed,11,1,12,2,1,37,52,...,0,0,0,1,0,2,0,1,0,Maharashtra
12,18-Mar-20,18-03-2020,Confirmed,37,25,17,11,0,27,30,...,3,0,1,8,0,2,1,0,0,Maharashtra
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1776,27-Oct-21,27-10-2021,Confirmed,16351,2,17,6,244,5,5,...,4,13,1075,186,18,13,17,976,0,Lakshdweep
1779,28-Oct-21,28-10-2021,Confirmed,14307,1,23,14,322,6,4,...,7,14,1061,171,15,11,8,990,0,Lakshdweep
1782,29-Oct-21,29-10-2021,Confirmed,14215,64,22,9,322,6,5,...,6,9,1039,174,11,9,7,982,0,Lakshdweep
1785,30-Oct-21,30-10-2021,Confirmed,12940,73,31,11,283,5,6,...,3,10,1021,168,10,18,15,980,0,Lakshdweep
1788,31-Oct-21,31-10-2021,Confirmed,12907,50,20,1,212,8,5,...,2,21,1009,121,12,6,5,914,0,Lakshdweep

,Date,Date_YMD,Status,Total,Hospitalized,Recovered,Deceased,Mask,Sanitizer,Oxygen,...,RJ,SK,TN,TG,TR,UP,UT,WB,UN,State
0,14-Mar-20,14-03-2020,Confirmed,81,12,120,0,10,60,48,...,3,0,1,1,0,12,0,0,0,Maharashtra
3,15-Mar-20,15-03-2020,Confirmed,27,89,15,0,40,41,57,...,1,0,0,2,0,1,0,0,0,Maharashtra
6,16-Mar-20,16-03-2020,Confirmed,15,1,14,7,70,28,55,...,0,0,0,1,0,0,1,0,0,Maharashtra
9,17-Mar-20,17-03-2020,Confirmed,11,1,12,2,1,37,52,...,0,0,0,1,0,2,0,1,0,Maharashtra
12,18-Mar-20,18-03-2020,Confirmed,37,25,17,11,0,27,30,...,3,0,1,8,0,2,1,0,0,Maharashtra
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1776,27-Oct-21,27-10-2021,Confirmed,16351,2,17,6,244,5,5,...,4,13,1075,186,18,13,17,976,0,Lakshdweep
1779,28-Oct-21,28-10-2021,Confirmed,14307,1,23,14,322,6,4,...,7,14,1061,171,15,11,8,990,0,Lakshdweep
1782,29-Oct-21,29-10-2021,Confirmed,14215,64,22,9,322,6,5,...,6,9,1039,174,11,9,7,982,0,Lakshdweep
1785,30-Oct-21,30-10-2021,Confirmed,12940,73,31,11,283,5,6,...,3,10,1021,168,10,18,15,980,0,Lakshdweep
1788,31-Oct-21,31-10-2021,Confirmed,12907,50,20,1,212,8,5,...,2,21,1009,121,12,6,5,914,0,Lakshdweep

In [22]:
active=patients[patients['Status']=='Confirmed'].shape[0]

In [23]:
active

597

597

In [24]:
recovered=patients[patients['Status']=='Recovered'].shape[0]

In [25]:
recovered

597

597

In [26]:
deceased=patients[patients['Status']=='Deceased'].shape[0]

In [27]:
deceased

597

597

In [28]:
total=patients.shape[0]
active=patients[patients['Status']=='Confirmed'].shape[0]
recovered=patients[patients['Status']=='Recovered'].shape[0]
deceased=patients[patients['Status']=='Deceased'].shape[0]

### for Graph of row 3

In [31]:
options1=[
    {'label':'All','value':'All'},
    {'label':'Hospitalized','value':'Hospitalized'},
    {'label':'Recovered','value':'Recovered'},
    {'label':'Deceased','value':'Deceased'},
    ]

In [32]:
options1

[{'label': 'All', 'value': 'All'},
 {'label': 'Hospitalized', 'value': 'Hospitalized'},
 {'label': 'Recovered', 'value': 'Recovered'},
 {'label': 'Deceased', 'value': 'Deceased'}]

[{'label': 'All', 'value': 'All'},
 {'label': 'Hospitalized', 'value': 'Hospitalized'},
 {'label': 'Recovered', 'value': 'Recovered'},
 {'label': 'Deceased', 'value': 'Deceased'}]